package com.ikkong.platform.controller;

import java.util.Map;
import com.ikkong.core.base.BaseController;
import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.platform.utils.MyDateUtil;
import com.ikkong.system.controller.base.UrlPermissController;
import com.ikkong.platform.model.Company;
import com.ikkong.platform.service.CompanyService;
import com.ikkong.platform.service.impl.CompanyServiceImpl;
import org.apache.poi.ss.usermodel.DateUtil;

/**
 * Generated by Blade.
 * 2017-11-22 14:55:28
 */
public class CompanyController extends UrlPermissController {
	private static String CODE = "company";
	private static String PERFIX = "company";
	private static String LIST_SOURCE = "Company.list";
	private static String BASE_PATH = "/platform/company/";
	
	CompanyService service = new CompanyServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "company.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "company_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Company company = service.findById(id);
		setAttr("model", JsonKit.toJson(company));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "company_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Company company = service.findById(id);
		setAttr("model", JsonKit.toJson(company));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "company_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Company company = mapping(PERFIX, Company.class);
		company.setUpdate_time(MyDateUtil.getNowDate());
		company.setCreate_time(MyDateUtil.getNowDate());
		boolean temp = service.save(company);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Company company = mapping(PERFIX, Company.class);
//		company.setVersion(company.getVersion()+1);
		boolean temp = service.update(company);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
