package com.ikkong.platform.controller;

import java.util.Map;
import com.ikkong.core.base.BaseController;
import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.system.controller.base.UrlPermissController;
import com.ikkong.platform.model.Task;
import com.ikkong.platform.service.TaskService;
import com.ikkong.platform.service.impl.TaskServiceImpl;

/**
 * Generated by Blade.
 * 2017-11-22 15:45:04
 */
public class TaskController extends UrlPermissController {
	private static String CODE = "task";
	private static String PERFIX = "task";
	private static String LIST_SOURCE = "Task.list";
	private static String BASE_PATH = "/platform/task/";
	
	TaskService service = new TaskServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "task.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "task_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Task task = service.findById(id);
		setAttr("model", JsonKit.toJson(task));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "task_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Task task = service.findById(id);
		setAttr("model", JsonKit.toJson(task));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "task_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Task task = mapping(PERFIX, Task.class);
		boolean temp = service.save(task);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Task task = mapping(PERFIX, Task.class);
//		task.setVersion(task.getVersion()+1);
		boolean temp = service.update(task);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
