package com.ikkong.platform.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-11-22 14:55:28
 */
@Table(name = "company")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Company extends BaseModel {
    	private Integer id; //业务编号
    	private Integer del_status; //是否删除 0:未删除 1:删除
    	private Integer product_id; //产品id
    	private Integer user_id; //用户id
    	private String address; //公司地址
    	private String desc; //公司描述
    	private String mobile; //联系电话
    	private String name; //公司名称
    	private String type; //公司类型
    	private Date create_time; //创建时间
    	private Date update_time; //修改时间

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getDel_status() {
    		return del_status;
    	}

    	public void setDel_status(Integer del_status) {
    		this.del_status = del_status;
    	}

    	public Integer getProduct_id() {
    		return product_id;
    	}

    	public void setProduct_id(Integer product_id) {
    		this.product_id = product_id;
    	}

    	public Integer getUser_id() {
    		return user_id;
    	}

    	public void setUser_id(Integer user_id) {
    		this.user_id = user_id;
    	}

    	public String getAddress() {
    		return address;
    	}

    	public void setAddress(String address) {
    		this.address = address;
    	}

    	public String getDesc() {
    		return desc;
    	}

    	public void setDesc(String desc) {
    		this.desc = desc;
    	}

    	public String getMobile() {
    		return mobile;
    	}

    	public void setMobile(String mobile) {
    		this.mobile = mobile;
    	}

    	public String getName() {
    		return name;
    	}

    	public void setName(String name) {
    		this.name = name;
    	}

    	public String getType() {
    		return type;
    	}

    	public void setType(String type) {
    		this.type = type;
    	}

    	public Date getCreate_time() {
    		return create_time;
    	}

    	public void setCreate_time(Date create_time) {
    		this.create_time = create_time;
    	}

    	public Date getUpdate_time() {
    		return update_time;
    	}

    	public void setUpdate_time(Date update_time) {
    		this.update_time = update_time;
    	}

}
