package com.ikkong.platform.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-11-20 11:19:32
 */
@Table(name = "user")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Customer extends BaseModel {
    	private Long id; //用户编号
    	private Integer gender;
    	private Integer status;
    	private Integer version;
    	private Long active_degree;
    	private String city;
    	private String email;
    	private String fk_resource_id;
    	private String head_img_url;
    	private String introduction;
    	private String mobile;
    	private String nick_name;
    	private String password;
    	private String province;
    	private String signature;
    	private Date birthday;
    	private Date registe_time;

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getGender() {
    		return gender;
    	}

    	public void setGender(Integer gender) {
    		this.gender = gender;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Long getActive_degree() {
    		return active_degree;
    	}

    	public void setActive_degree(Long active_degree) {
    		this.active_degree = active_degree;
    	}

    	public String getCity() {
    		return city;
    	}

    	public void setCity(String city) {
    		this.city = city;
    	}

    	public String getEmail() {
    		return email;
    	}

    	public void setEmail(String email) {
    		this.email = email;
    	}

    	public String getFk_resource_id() {
    		return fk_resource_id;
    	}

    	public void setFk_resource_id(String fk_resource_id) {
    		this.fk_resource_id = fk_resource_id;
    	}

    	public String getHead_img_url() {
    		return head_img_url;
    	}

    	public void setHead_img_url(String head_img_url) {
    		this.head_img_url = head_img_url;
    	}

    	public String getIntroduction() {
    		return introduction;
    	}

    	public void setIntroduction(String introduction) {
    		this.introduction = introduction;
    	}

    	public String getMobile() {
    		return mobile;
    	}

    	public void setMobile(String mobile) {
    		this.mobile = mobile;
    	}

    	public String getNick_name() {
    		return nick_name;
    	}

    	public void setNick_name(String nick_name) {
    		this.nick_name = nick_name;
    	}

    	public String getPassword() {
    		return password;
    	}

    	public void setPassword(String password) {
    		this.password = password;
    	}

    	public String getProvince() {
    		return province;
    	}

    	public void setProvince(String province) {
    		this.province = province;
    	}

    	public String getSignature() {
    		return signature;
    	}

    	public void setSignature(String signature) {
    		this.signature = signature;
    	}

    	public Date getBirthday() {
    		return birthday;
    	}

    	public void setBirthday(Date birthday) {
    		this.birthday = birthday;
    	}

    	public Date getRegiste_time() {
    		return registe_time;
    	}

    	public void setRegiste_time(Date registe_time) {
    		this.registe_time = registe_time;
    	}

}
