package com.ikkong.platform.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-11-22 14:55:28
 */
@Table(name = "message")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Message extends BaseModel {
    	private Integer id; //业务id
    	private Integer del_status; //0:未删除 1:删除
    	private Integer resource_id; //资源id
    	private String desc; //消息内容
    	private String name; //名称
    	private String type; //类型
    	private Date create_time; //创建时间
    	private Date update_time; //修改时间

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getDel_status() {
    		return del_status;
    	}

    	public void setDel_status(Integer del_status) {
    		this.del_status = del_status;
    	}

    	public Integer getResource_id() {
    		return resource_id;
    	}

    	public void setResource_id(Integer resource_id) {
    		this.resource_id = resource_id;
    	}

    	public String getDesc() {
    		return desc;
    	}

    	public void setDesc(String desc) {
    		this.desc = desc;
    	}

    	public String getName() {
    		return name;
    	}

    	public void setName(String name) {
    		this.name = name;
    	}

    	public String getType() {
    		return type;
    	}

    	public void setType(String type) {
    		this.type = type;
    	}

    	public Date getCreate_time() {
    		return create_time;
    	}

    	public void setCreate_time(Date create_time) {
    		this.create_time = create_time;
    	}

    	public Date getUpdate_time() {
    		return update_time;
    	}

    	public void setUpdate_time(Date update_time) {
    		this.update_time = update_time;
    	}

}
