package com.ikkong.platform.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-11-22 15:45:04
 */
@Table(name = "task")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Task extends BaseModel {
    	private Integer id; //业务id
    	private Integer del_status; //0:未删除 1:删除
    	private Integer user_id; //用户id
    	private String address; //发布地址
    	private String desc; //相关描述
    	private String dev_time; //任务完成周期
    	private String name; //任务名称
    	private String price; //价格
    	private String type; //类型
    	private Date create_time; //创建时间
    	private Date update_time; //修改时间

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getDel_status() {
    		return del_status;
    	}

    	public void setDel_status(Integer del_status) {
    		this.del_status = del_status;
    	}

    	public Integer getUser_id() {
    		return user_id;
    	}

    	public void setUser_id(Integer user_id) {
    		this.user_id = user_id;
    	}

    	public String getAddress() {
    		return address;
    	}

    	public void setAddress(String address) {
    		this.address = address;
    	}

    	public String getDesc() {
    		return desc;
    	}

    	public void setDesc(String desc) {
    		this.desc = desc;
    	}

    	public String getDev_time() {
    		return dev_time;
    	}

    	public void setDev_time(String dev_time) {
    		this.dev_time = dev_time;
    	}

    	public String getName() {
    		return name;
    	}

    	public void setName(String name) {
    		this.name = name;
    	}

    	public String getPrice() {
    		return price;
    	}

    	public void setPrice(String price) {
    		this.price = price;
    	}

    	public String getType() {
    		return type;
    	}

    	public void setType(String type) {
    		this.type = type;
    	}

    	public Date getCreate_time() {
    		return create_time;
    	}

    	public void setCreate_time(Date create_time) {
    		this.create_time = create_time;
    	}

    	public Date getUpdate_time() {
    		return update_time;
    	}

    	public void setUpdate_time(Date update_time) {
    		this.update_time = update_time;
    	}

}
