package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.platform.model.Company;
import com.ikkong.platform.service.CompanyService;

/**
 * Generated by Blade.
 * 2017-11-22 14:55:28
 */
public class CompanyServiceImpl extends BaseService<Company> implements CompanyService{

}
