package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.platform.model.Customer;
import com.ikkong.platform.service.CustomerService;

/**
 * Generated by Blade.
 * 2017-11-22 14:55:28
 */
public class CustomerServiceImpl extends BaseService<Customer> implements CustomerService{

}
