package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.platform.model.Message;
import com.ikkong.platform.service.MessageService;

/**
 * Generated by Blade.
 * 2017-11-22 14:55:28
 */
public class MessageServiceImpl extends BaseService<Message> implements MessageService{

}
