package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.platform.model.Task;
import com.ikkong.platform.service.TaskService;

/**
 * Generated by Blade.
 * 2017-11-22 15:45:04
 */
public class TaskServiceImpl extends BaseService<Task> implements TaskService{

}
