package com.ikkong.platform.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.platform.model.Company;

/**
 * Generated by Blade.
 * 2017-11-22 14:55:28
 */
public interface CompanyService extends IService<Company>{

}
