package com.ikkong.platform.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.platform.model.Customer;

/**
 * Generated by Blade.
 * 2017-11-20 11:19:32
 */
public interface CustomerService extends IService<Customer>{

}
