package com.ikkong.platform.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.platform.model.Message;

/**
 * Generated by Blade.
 * 2017-11-22 14:55:28
 */
public interface MessageService extends IService<Message>{

}
