package com.ikkong.platform.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.platform.model.Task;

/**
 * Generated by Blade.
 * 2017-11-22 15:45:04
 */
public interface TaskService extends IService<Task>{

}
